const I18N = {
en: {
  "nav.services": "Services",
  "nav.why": "Why us",
  "nav.gallery": "Gallery",
  "nav.faq": "FAQ",
  "nav.reviews": "Reviews",
  "nav.contact": "Contact",
  "nav.call": "04 339 2930",
  "nav.whatsapp": "WhatsApp",
  "hero.kicker": "Al Quoz, Dubai · Electrical & plumbing",
  "hero.title": "Your wiring and pipes,<br>sorted in one visit.",
  "hero.sub": "Electrical and plumbing installation plus repairs — one team for homes and workplaces across Dubai. Based in Al Quoz Industrial Area, serving all of Dubai.",
  "hero.cta1": "Book a visit",
  "hero.cta2": "WhatsApp us",
  "trust.t1t": "Call us",
  "trust.t1d": "04 339 2930",
  "trust.t2t": "Electrical · Plumbing",
  "trust.t2d": "Installation & repairs",
  "trust.t3t": "Al Quoz based",
  "trust.t3d": "Serving all of Dubai",
  "stats.samedayNum": "Call today",
  "stats.sameday": "one team for both trades",
  "stats.tradesNum": "Electrical + plumbing",
  "stats.trades": "installation specialists",
  "stats.rateNum": "Al Quoz",
  "stats.rate": "serving all Dubai",
  "stats.visitNum": "Quote first",
  "stats.visit": "clear pricing before work",
  "services.kicker": "What we do",
  "services.title": "Installation and repair, done right",
  "services.s1t": "Electrical installation",
  "services.s1d": "New wiring, panels and sockets — installed to a professional standard.",
  "services.s2t": "Electrical repairs",
  "services.s2d": "Fault finding and repairs for switches, sockets and circuits.",
  "services.s3t": "Plumbing installation",
  "services.s3d": "Pipework and sanitary fittings installed cleanly and correctly.",
  "services.s4t": "Plumbing repairs",
  "services.s4d": "Leaks, blockages and faulty fittings — repaired quickly and neatly.",
  "services.s5t": "Lighting & fixtures",
  "services.s5d": "Indoor and outdoor lighting installed and repaired.",
  "services.s6t": "Pumps & fittings",
  "services.s6d": "Water pumps, taps and valves installed and serviced.",
  "why.kicker": "Why choose us",
  "why.title": "Two trades, one team",
  "why.intro": "Electrical and plumbing work needs to be done right — our Al Quoz team installs and repairs with care, and you approve the price before we begin.",
  "why.l1t": "One team",
  "why.l1d": "Electrical and plumbing together — no juggling two contractors.",
  "why.l2t": "Al Quoz based",
  "why.l2d": "Quick to reach anywhere in Dubai from our workshop.",
  "why.l3t": "Upfront pricing",
  "why.l3d": "You approve the price before we begin — no surprises.",
  "why.l4t": "Easy to reach",
  "why.l4d": "Call or WhatsApp on 04 339 2930 — we will take it from there.",
  "gallery.kicker": "Our work",
  "gallery.title": "Neat work, done properly",
  "gallery.c1": "Neat electrical panels, wired safely",
  "gallery.c2": "Sanitary fittings, clean finish",
  "gallery.c3": "Tap and pipe repairs without the mess",
  "reviews.kicker": "What people say",
  "reviews.title": "Trusted across Dubai",
  "reviews.more": "Find us on Google — see our location and reviews",
  "faq.kicker": "Good to know",
  "faq.title": "Frequently asked questions",
  "faq.q1": "Which areas do you serve?",
  "faq.a1": "We are based in Al Quoz Industrial Area and serve homes and workplaces across Dubai.",
  "faq.q2": "Do you give quotes before starting?",
  "faq.a2": "Yes — you approve the price before we begin any work. No surprises.",
  "faq.q3": "Do you handle both electrical and plumbing?",
  "faq.a3": "Yes — one team does both, so you only book one visit.",
  "faq.q4": "How do I book a visit?",
  "faq.a4": "Call or WhatsApp us on 04 339 2930 and tell us what needs fixing — we will take it from there.",
  "contact.kicker": "Get in touch",
  "contact.title": "Book your visit",
  "contact.addr": "Address",
  "contact.phone": "Phone",
  "contact.hours": "Hours",
  "contact.hoursVal": "Hours: by appointment | Call for availability",
  "contact.cta": "Call to book",
  "contact.cta2": "WhatsApp us",
  "footer.tag": "Electrical & plumbing installation · Al Quoz, Dubai"
}};

document.addEventListener("DOMContentLoaded", function () {
  var btn = document.getElementById("menuBtn");
  var nav = document.getElementById("mainNav");
  if (btn && nav) { btn.addEventListener("click", function () { nav.classList.toggle("open"); }); }
  nav && nav.querySelectorAll("a").forEach(function (a) { a.addEventListener("click", function () { nav.classList.remove("open"); }); });
  var dict = I18N.en || {};
  document.querySelectorAll("[data-i18n]").forEach(function (el) {
    var k = el.getAttribute("data-i18n");
    if (dict[k] !== undefined) { el.innerHTML = dict[k]; }
  });
});
